[SerialPort]
port = "COM7"
baudrate = 115200
password = "1234"

[SerialPort.config]
rele1 = false
rele2 = true
rele3 = false
rele4 = false
rele5 = false

[Webcam]
password = "1234"

[Client]
id = "laboratorio.remoto"
secret = "secreto"
redirectUri = "http://127.0.0.1:3000/main.html"

[Session]
secret = "ananashe"